on:
  push:
    branches:
      - main
jobs:
  publish:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        version: [23.x]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.version }}
      - uses: actions/checkout@v4
      - run: npm ci
      - run: npm run publish
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NODE_OPTIONS: "--no-experimental-strip-types"